name: mpass
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.6.0

dependencies:
    flutter:
        sdk: flutter
    dynamic_color: ^1.7.0
    provider: ^6.1.2
    http: ^1.3.0
    flutter_secure_storage: ^9.2.4
    local_auth: ^2.3.0
    convert: ^3.1.2
    crypto: ^3.0.6
    cryptography: ^2.7.0
    dart_jsonwebtoken: ^2.17.0
    flutter_native_splash: ^2.4.4
    lottie: ^3.3.1
    shimmer: ^3.0.0
    pointycastle: ^3.9.1
    intl: ^0.19.0
    path_provider: ^2.1.5
    pinput: ^5.0.1
    file_picker: ^9.0.2
    hive_ce: ^2.10.1
    build_runner: ^2.4.15
    hive_ce_generator: ^1.8.2
    hive_ce_flutter: ^2.2.0
    connectivity_plus: ^6.1.3
    flutter_displaymode: ^0.6.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/m_pass.png
        - assets/m_pass_white.png
        - assets/mPass_lottie.json
        - assets/mPass_lottie_dark.json
        - assets/words.txt


flutter_native_splash:
      color: "#E8F0FE"
      image: assets/m_pass.png
      android: true
      ios: true
      android_gravity: center
      ios_content_mode: scaleAspectFit
      color_dark: "#1A202A" 
      image_dark: assets/m_pass_white.png